openapi: 3.0.0
info:
 title: httpbin API
 description: Simple API for testing purposes
 version: 1.0.0
servers:
 - url: http://httpbin.org
paths:
 /request:
   get:
     summary: Get a simple response from the /request resource of the httpbin API
     responses:
       '200':
         description: Successful response
